spring:
  ai:
    model:
      chat: google-genai
      embedding: ollama # embedding sempre no Ollama, mesmo com chat na nuvem
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          model: gemini-2.5-flash
          max-output-tokens: 1024
          temperature: 0.1
    ollama:
      base-url: localhost:11435 # porta do container Ollama no compose
      embedding:
        model: bge-m3
    vectorstore:
      pgvector:
        dimensions: 1024 #casa com a saida do bge-m3